apiVersion: batch/v1
kind: Job
metadata:
  name: job-name                # Replace with job name
spec:
  template:
    spec:
      containers:
        - name: container-name  # Replace with container name
          image: image-name     # Replace with image (e.g., busybox)
          command: ["echo", "Hello Kubernetes"]  # Replace command as needed
      restartPolicy: Never
  backoffLimit: 4               # Number of retries before considering failed
