apiVersion: v1
kind: Secret
metadata:
  name: secret-name             # Replace with secret name
type: Opaque
data:
  username: dXNlcm5hbWU=        # Base64-encoded value (e.g., echo -n 'username' | base64)
  password: cGFzc3dvcmQ=        # Base64-encoded value (e.g., echo -n 'password' | base64)
