apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default           # Replace with target namespace
  name: role-name              # Replace with Role name
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]  # Customize permissions
