apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-name       # Replace with RoleBinding name
  namespace: default           # Replace with namespace
subjects:
  - kind: ServiceAccount
    name: sa-name              # Replace with ServiceAccount name
    namespace: default
roleRef:
  kind: Role
  name: role-name              # Replace with Role name
  apiGroup: rbac.authorization.k8s.io
