apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding-name  # Replace with ClusterRoleBinding name
subjects:
  - kind: ServiceAccount
    name: sa-name                # Replace with ServiceAccount name
    namespace: default
roleRef:
  kind: ClusterRole
  name: clusterrole-name         # Replace with ClusterRole name
  apiGroup: rbac.authorization.k8s.io
